spring:
  rabbitmq:
    host: {{ include "shiftcontrol.rabbitmqHost" . }}
    port: {{ .Values.rabbitmq.service.amqpPort }}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oidc.provider.issuer-uri}

oidc:
  provider:
    issuer-uri: ${SHIFTCONTROL_OIDC_ISSUER_URI}
    allowed-issuers:
    - ${SHIFTCONTROL_OIDC_ISSUER_URI}

shiftcontrol:
  domain: ${SHIFTCONTROL_DOMAIN}
