spring:
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: {{ include "shiftcontrol.rabbitmqHost" . }}
    port: {{ .Values.rabbitmq.service.amqpPort }}
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oidc.provider.issuer-uri}
logging:
  level:
    root: INFO

oidc:
  provider:
    issuer-uri: ${SHIFTCONTROL_OIDC_ISSUER_URI}
    allowed-issuers:
    - ${SHIFTCONTROL_OIDC_ISSUER_URI}

shiftcontrol:
  domain: ${SHIFTCONTROL_DOMAIN}
  internal-api:
    key: ${SHIFTCONTROL_INTERNAL_API_KEY:}
