spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SHIFTCONTROL_OIDC_ISSUER_URI}

oidc:
  provider:
    issuer-uri: ${SHIFTCONTROL_OIDC_ISSUER_URI}
    allowed-issuers:
      - ${SHIFTCONTROL_OIDC_ISSUER_URI}
      - ${SHIFTCONTROL_OIDC_PUBLIC_ISSUER_URI:${SHIFTCONTROL_OIDC_ISSUER_URI}}

shiftcontrol:
  domain: ${SHIFTCONTROL_DOMAIN}

keycloak:
  auth-server-url: ${SHIFTCONTROL_OIDC_BASE_URL}/
  auth-realm: ${SHIFTCONTROL_OIDC_REALM}
  client:
    id: admin-cli
    realm: master
    username: ${KEYCLOAK_ADMIN}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
