spring:
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SHIFTCONTROL_OIDC_ISSUER_URI}
logging:
  level:
    root: INFO

oidc:
  provider:
    issuer-uri: ${SHIFTCONTROL_OIDC_ISSUER_URI}
    allowed-issuers:
      - ${SHIFTCONTROL_OIDC_ISSUER_URI}
      - ${SHIFTCONTROL_OIDC_PUBLIC_ISSUER_URI:${SHIFTCONTROL_OIDC_ISSUER_URI}}

shiftcontrol:
  domain: ${SHIFTCONTROL_DOMAIN}
  internal-api:
    key: ${SHIFTCONTROL_INTERNAL_API_KEY:}

keycloak:
  auth-server-url: ${SHIFTCONTROL_OIDC_BASE_URL}/
  auth-realm: ${SHIFTCONTROL_OIDC_REALM}
  client:
    id: admin-cli
    realm: master
    username: ${KEYCLOAK_ADMIN}
    password: ${KEYCLOAK_ADMIN_PASSWORD}
