services:
  shiftcontrol-frontend:
    image: "ghcr.io/pilotwhale-os/shiftcontrol/dashboard:latest"
    container_name: "shiftcontrol-dashboard"
    networks:
      - shiftcontrol
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`frontend.127.0.0.1.nip.io`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.services.frontend.loadbalancer.server.port=8080
      # - traefik.http.routers.frontend.middlewares=jwt-auth@file

networks:
  shiftcontrol:
    external: true