services:

  traefik:
    image: "traefik:latest"
    container_name: "shiftcontrol-infra-traefik"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/traefik.yml:ro"
      - "./config/traefik-dynamic.yml:/configurations/traefik-dynamic.yml"
    networks:
      - shiftcontrol
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.127.0.0.1.nip.io`)
      - traefik.http.routers.traefik.service=api@internal
    ports:
      - "80:80"

  keycloak:
    image: "quay.io/keycloak/keycloak:26.0.0"
    container_name: "shiftcontrol-infra-keycloak"
    hostname: keycloak
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command:
      - start-dev
      - --import-realm
      - --log-level=INFO
    volumes:
      - ./config/realm-dev.json:/opt/keycloak/data/import/realm-dev.json
    networks:
      - shiftcontrol
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.entrypoints=web
      - traefik.http.routers.keycloak.rule=Host(`keycloak.127.0.0.1.nip.io`)
      - traefik.http.services.keycloak.loadbalancer.server.port=8080

  postgres:
    image: "postgres:latest"
    container_name: "shiftcontrol-infra-postgres"
    hostname: postgres
    environment:
      POSTGRES_USER: "shiftcontrol"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "shiftservice"
    networks:
      - shiftcontrol
    volumes:
      - postgres-data:/var/lib/postgresql

  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: "shiftcontrol-infra-pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - shiftcontrol
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.entrypoints=web
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.127.0.0.1.nip.io`)
      - traefik.http.services.pgadmin.loadbalancer.server.port=80

  rabbitmq:
    image: "rabbitmq:4-management"
    container_name: "shiftcontrol-infra-rabbitmq"
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: shiftcontrol
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - shiftcontrol

  redis:
    image: "redis:7-alpine"
    container_name: "shiftcontrol-infra-redis"
    networks:
      - shiftcontrol

networks:
  shiftcontrol:
    external: true

volumes:
  postgres-data:
  pgadmin-data:
  rabbitmq-data: