spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: shiftcontrol
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/prod

keycloak:
  auth-server-url: http://keycloak:8080/
  auth-realm: prod
  allowed-issuers:
    - https://${SHIFTCONTROL_KEYCLOAK_DOMAIN:keycloak.shiftcontrol.example.com}/realms/prod
    - http://keycloak:8080/realms/prod
  client:
    id: admin-cli
    realm: master
    username: admin
    password: admin

shiftcontrol:
  domain: ${SHIFTCONTROL_DOMAIN:shiftcontrol.example.com}
  keycloak-domain: ${SHIFTCONTROL_KEYCLOAK_DOMAIN:keycloak.shiftcontrol.example.com}
