spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:shiftcontrol}
    password: ${RABBITMQ_DEFAULT_PASS}
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${oidc.provider.issuer-uri}

oidc:
  provider:
    issuer-uri: http://keycloak:8080/realms/prod
    allowed-issuers:
    - https://${SHIFTCONTROL_KEYCLOAK_DOMAIN:keycloak.shiftcontrol.example.com}/realms/prod
    - http://keycloak:8080/realms/prod

shiftcontrol:
  domain: ${SHIFTCONTROL_DOMAIN:shiftcontrol.example.com}
  keycloak-domain: ${SHIFTCONTROL_KEYCLOAK_DOMAIN:keycloak.shiftcontrol.example.com}
