spring:
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/prod
logging:
  level:
    root: INFO

keycloak:
  auth-server-url: http://keycloak:8080/
  auth-realm: prod
  allowed-issuers:
    - https://keycloak.shiftcontrol.example.com/realms/prod
    - http://keycloak:8080/realms/prod
  client:
    id: admin-cli
    realm: master
    username: admin
    password: admin
