spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:shiftcontrol}
    password: ${RABBITMQ_DEFAULT_PASS}
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: redis
      port: 6379

trust:
  shiftservice:
    baseUrl: http://shiftservice:8080/
    endpoint: api/v1/trust-alerts
    apiKey:
  oauth2:
    client:
      tokenUrl: http://keycloak:8080/realms/prod/protocol/openid-connect/token
      clientId: internal
      clientSecret: change-me
      scope:
  rabbitmq:
    exchange: shiftcontrol
    queue: trust-service
    routing-key: shiftcontrol.#

shiftcontrol:
  domain: ${SHIFTCONTROL_DOMAIN:shiftcontrol.example.com}
  keycloak-domain: ${SHIFTCONTROL_KEYCLOAK_DOMAIN:keycloak.shiftcontrol.example.com}
