services:
  shiftcontrol-frontend:
    image: "ghcr.io/pilotwhale-os/shiftcontrol/dashboard:latest"
    container_name: "shiftcontrol-dashboard"
    environment:
      KEYCLOAK_URL: https://keycloak.shiftcontrol.example.com
      KEYCLOAK_REALM: prod
      KEYCLOAK_CLIENT_ID: frontend
      SHIFTSERVICE_BASE_PATH: https://shiftservice.shiftcontrol.example.com
      AUDITSERVICE_BASE_PATH: https://auditservice.shiftcontrol.example.com
      NOTIFICATIONSERVICE_BASE_PATH: https://notificationservice.shiftcontrol.example.com
    networks:
      - shiftcontrol
      - traefik-nw
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-nw
      - traefik.http.routers.frontend.rule=Host(`frontend.shiftcontrol.example.com`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.services.frontend.loadbalancer.server.port=8080
      # - traefik.http.routers.frontend.middlewares=jwt-auth@file

networks:
  shiftcontrol:
    external: true
  traefik-nw:
    external: true