services:
  keycloak:
    image: "quay.io/keycloak/keycloak:26.0.0"
    container_name: "keycloak"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KC_HOSTNAME: keycloak.shiftcontrol.arcs.sh
      KC_HTTP_ENABLED: 'true'
      KC_PROXY_HEADERS: 'xforwarded'
      PROXY_ADDRESS_FORWARDING: 'true'
    command:
      - start
      - --import-realm
      - --log-level=INFO
    networks:
      - shiftcontrol
      - tobeh
    volumes:
      - ./realm-dev.json:/opt/keycloak/data/import/realm-dev.json
    labels:
      - traefik.enable=true
      - traefik.docker.network=tobeh
      - traefik.http.routers.keycloak.entrypoints=websecure
      - traefik.http.routers.keycloak.rule=Host(`keycloak.shiftcontrol.arcs.sh`)
      - traefik.http.services.keycloak.loadbalancer.server.port=8080

  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    environment:
      POSTGRES_USER: "shiftcontrol"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "shiftservice"
    networks:
      - shiftcontrol
    volumes:
      - postgres-data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - shiftcontrol
      - tobeh
    labels:
      - traefik.enable=true
      - traefik.docker.network=tobeh
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.shiftcontrol.arcs.sh`)
      - traefik.http.services.pgadmin.loadbalancer.server.port=80

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: shiftcontrol
      RABBITMQ_DEFAULT_PASS: password
      # optional: default vhost ("/" by default)
      # RABBITMQ_DEFAULT_VHOST: /
    networks:
      - shiftcontrol
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

networks:
  shiftcontrol:
    external: true
  tobeh:
    external: true

volumes:
  postgres-data:
  pgadmin-data:
  rabbitmq-data: