{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shiftcontrol.secretName" . }}
  labels:
    {{- include "shiftcontrol.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-username: {{ .Values.postgres.auth.username | quote }}
  postgres-password: {{ .Values.postgres.auth.password | quote }}
  rabbitmq-username: {{ .Values.rabbitmq.auth.username | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.auth.password | quote }}
  internal-api-key: {{ .Values.global.internalApiKey | quote }}
  oidc-client-secret: {{ .Values.global.keycloakInternalClientSecret | quote }}
  smtp-username: {{ .Values.notificationservice.email.smtpUsername | quote }}
  smtp-password: {{ .Values.notificationservice.email.smtpPassword | quote }}
  pgadmin-email: {{ .Values.pgadmin.credentials.email | quote }}
  pgadmin-password: {{ .Values.pgadmin.credentials.password | quote }}
{{- end }}
